### PR TITLE
sim_translators: Update node_map_to_path.py to work with the new EUFS simulator

### PR DESCRIPTION
**Pull request by supex0fan**

### CODE REVIEW

**Comment by supex0fan** [comment]
Closed whilst I work on sorting the received cones.

**Comment by supex0fan** [comment]
Hold on, I've made some more optimisations, will push them soon.

**Comment by b1n-ch1kn** [comment]
image
hmm smth doesn't seem right about this one lol
I adjusted the .csv location of cones do the car was centred and the left and right orange logic worked.

**Comment by supex0fan** [comment]
Which track is that? Did the csv changes fix the problem?

**Comment by b1n-ch1kn** [comment]
That's QR 2022. the csv changes meant it could find 2 oranges to the left of 0,0 and 2 to the right. Before then it was erroring because all 4 oranges were to the left of 0,0.
So i was able to run it and it was a bit squiggly. Also tried it on one of the other eufs tracks, peanut, and i got a similar squiggle

**Comment by supex0fan** [comment]
My optimization was too aggressive. Will have to watch that hard distance limit, realistically it can be a very large number without hitting performance too hard, something like 100 wouldn't be a problem if it is missing cones.

**Review by b1n-ch1kn — APPROVED** [review]

**Pull request merged**
