### PR TITLE
Add error in cone search range

### PR DESCRIPTION
**Pull request by supex0fan**
Works on small track :)

### CODE REVIEW

**Comment by b1n-ch1kn** [comment]
Would be more inclined to fix this in the sim so it's a rules spec track.
Plus this changed at track like the first thing we tried so probably going to be variable depending

**Comment by supex0fan** [comment]
Yea putting it as a variable is a good idea, can do that in this PR.

**Comment by supex0fan** [comment]
Ok how do you add it as a parameter? Do you mean in the ROS sense, like `self.declare_parameter('search_dist', 6)`, or from a file?

**Comment by b1n-ch1kn** [comment]
> Ok how do you add it as a parameter? Do you mean in the ROS sense, like `self.declare_parameter('search_dist', 6)`, or from a file?

Both, the ROS params can be loaded from a .yaml file if they are declared like that (we do that in most packages these days rather than hard-coding)

**Comment by b1n-ch1kn** [comment]
We can yeet this now

**Pull request closed without merging**
